# ==========================================
# 1. APPLICATION INFO
# ==========================================
spring.application.name=authApi
server.port=8080

# ==========================================
# 2. DATABASE CONNECTION (The Godown)
# ==========================================
# 'auth_db' tumhare database ka naam hoga. 
# Aage wala flag usko khud create kar dega agar wo pehle se nahi hai.
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 3. HIBERNATE / JPA SETTINGS (Table Creator)
# ==========================================
# 'update' ka matlab hai ki Spring Boot tumhari User class dekh kar 
# MySQL mein khud ba khud tables aur columns bana dega.
spring.jpa.hibernate.ddl-auto=update

# (Optional) Ye console mein SQL queries dikhayega, debugging ke liye mast hai
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true